# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - hand_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 1.0

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  hand_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 1.0
    default: true
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint