# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - hand_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - end_effector_roll_virtual_joint
      - end_effector_yaw_virtual_joint
  hand_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint